# Generated by Django 2.0.7 on 2018-07-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACDB_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='review',
            new_name='reviewed',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='code',
            new_name='sourceCode',
        ),
    ]
