# Generated by Django 2.0.5 on 2018-07-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACDB_app', '0002_auto_20180721_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='reviewed',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='sourceCode',
            new_name='source',
        ),
    ]
