# Generated by Django 2.0.5 on 2018-07-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACDB_app', '0003_auto_20180723_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source',
            new_name='sourceCode',
        ),
    ]
